### ISSUE TITLE
Building test suite fails on Windows

### ISSUE THREAD

**Issue by hamishwillee** [Auterion/mavlink-testing-suite#13]
README instructions for building are 
```
(mkdir -p build && cd build && cmake .. && make)
```
There is no additional information about restrictions to platform or dependencies, so my assumption is that it can run on any platform and will install any dependencies if not.

So bug is either broken code, or incomplete readme listing of dependencies/platforms.

This failed on Windows and Ubuntu Linux in same place
- windows 10 : https://gist.github.com/hamishwillee/63d73e88f35c8abdf05488a495579bd2
- Ubuntu Linux 16.04 - https://gist.github.com/hamishwillee/e11c1a430aad9b8db4cab8f013b6a12a

**Comment by bkueng** [comment]
This comes from the SDK. Your're probably missing `libcurl4-openssl-dev`. We need to ensure the SDK deps are installed, so link to https://sdk.dronecode.org/en/contributing/build.html#build_sdk_cpp.

**Comment by hamishwillee** [comment]
Thanks @bkueng I will test the dependencies. 
In addition to pointing to the SDK dependencies we should say that there is no need to actually install the kit, because that gets done for you.

**Comment by julianoes** [comment]
Thanks @hamishwillee for trying. I'd say we should try to automate the dependencies for Windows and Linux in the SDK and than take advantage of it here.

**Comment by hamishwillee** [comment]
:-) I'm very trying

**Comment by JonasVautherin** [comment]
> I'd say we should try to automate the dependencies for Windows and Linux in the SDK and than take advantage of it here.

I'd rather go the other way: ideally, we should not build the SDK from this project, but depend on it (i.e. `find_package(DronecodeSDK REQUIRED)`). And then this issue becomes a DronecodeSDK issue instead of a mavlink-testing-suite one.

Managing dependencies from inside cmake does not scale, IMO. If possible, we can provide a way to build the dependencies, but I believe this should be independent from the project itself (I'm working on that for the SDK, actually).
